camera:
  - "0"
  - "1"
  - "2"
  - "3"
  - A12
  - B12
  - C9
  - D4
  - D6
  - D8
  - D9
  - E1
  - E2
  - E3
  - E4
  - E5
  - E6
  - E7
  - E8
  - E9
  - E10
  - F1
  - F2
  - F3
  - F4
  - F5
  - G1
  - G2
  - G3
  - G4
  - G5

index:
