batch_size: [1024]
epoch: [2000]
learning_rate: [0.002]
num_workers: [4]
shuffle: [True]

conv_ch_1: [32, 64]
conv_ch_2: [32, 64]
conv_ch_3: [32, 64]
conv_ks_1: [3, 5, 7]
conv_ks_2: [3, 5, 7]
conv_ks_3: [3, 5, 7]
